### ISSUE TITLE
Technology filter

### ISSUE THREAD

**Issue by babakkhavari** [kartoza/least-cost-electrification-benin#57]
Technology filter does not work for hybrid Diesel-PV and Diesel-Wind (when you uncheck them they do not dissapear like they do for the other technologies

**Comment by meomancer** [comment]
could you explain what you did and what it should be? it's not clear for me

**Comment by babakkhavari** [comment]
When you go the filters and uncheck one of the technologies it is supposed to dissapear from the map and the summaries. It does so for all other technologies but not for they hybrid technologies.

**Comment by meomancer** [comment]
On my side, they dissapear on the map and summary (notice no PV or Wind on summary and map)
![Selection_020](https://user-images.githubusercontent.com/4530905/93049953-3bf52f80-f68c-11ea-8f91-fed274264f50.png)

And also there is no PV and Wind on my summary and my maps if i turn them on
![Selection_021](https://user-images.githubusercontent.com/4530905/93050096-75c63600-f68c-11ea-93e1-922527e9908b.png)

maybe could you explain using image?

**Comment by babakkhavari** [comment]
yeah, actually you seem to be right, but could we remove PV-Diesel hybrid from legend when it is unchecked (see image below)

**Comment by babakkhavari** [comment]
yeah, actually you seem to be right, but could we remove PV-Diesel hybrid from legend when it is unchecked (see image below)
![image](https://user-images.githubusercontent.com/35455877/93050759-bcec0100-f663-11ea-9d76-9edef74660bb.png)
![image](https://user-images.githubusercontent.com/35455877/93050848-e147dd80-f663-11ea-9e75-f5c9f9ae6d06.png)

**Comment by meomancer** [comment]
hm... weird, mine is not like yours @babakkhavari 
i don't see any data instead just grid and Photovoltaic
did you use https://benin.gep.kartoza.com/gep/explore/bj-1?

**Comment by babakkhavari** [comment]
Yes

**Comment by meomancer** [comment]
what lever did you use @babakkhavari ?
maybe the screenshot of scenario page would be great

**Comment by babakkhavari** [comment]
![image](https://user-images.githubusercontent.com/35455877/93051750-418b4f00-f665-11ea-8619-7607d38f7370.png)
Everything else default

**Comment by meomancer** [comment]
great, now i understand the problem @babakkhavari

**Comment by meomancer** [comment]
hi @babakkhavari 
about this ticket, i think it is not bug

The problem is there is data for previous year that is in unchecked technology
The filters is working like this:
- we select 2030 and filter, for example just Grid
- It will fetch the data just for 2030 which is Grid
- After that it will check those filtered data to check technology for 2025 and also 2020
- it turns out some data has in different technology in 2025 

Example ID 61889
I filtered by Grid (1)
![Selection_034](https://user-images.githubusercontent.com/4530905/93288961-47209a80-f807-11ea-8505-209648c7e592.png)

The FinalElecCode2030 is 1 but FinalElecCode2025 is 8
And the it will be rendered in the chart
![Selection_035](https://user-images.githubusercontent.com/4530905/93288848-0aed3a00-f807-11ea-8a49-8d733fc59e7a.png)

That why there is legend for that, for the colors on chart

**Comment by babakkhavari** [comment]
Ok, is there a quick fix to this? It would make sense to change it

**Comment by meomancer** [comment]
what should be changed @babakkhavari ?
is it the csv? or the Summary? i think that is the logic on bep

**Comment by meomancer** [comment]
hi @babakkhavari do you mean that when we select som technology on a year, although the last year is not the selected technology, we should not show it on the population connected graph?

**Comment by babakkhavari** [comment]
Fixed
